name: sanchu6b
description: "PageAで得たデータAをPageBで使う練習"
publish_to: 'none' # pub.dev に公開したい場合はこの行を削除してください。
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  go_router:
  flutter_riverpod:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    # 日本語化するために0.18.1 を　0.18.0 にする必要あり(2023.6.11)
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  connectivity_plus: ^6.0.3
  # ■■■■■■■■■動画を再生するために必要なパッケージ■■■■■■■■■
  #video_player: ^2.8.5
  #youtube_player_flutter: ^9.0.1
  youtube_player_iframe: ^5.1.2
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  #  #スプラッシュ画面作成用
  #  flutter_native_splash: ^2.2.7
  #flutter_native_splash:
  #  image: "assets/images/icon/icon_uranai_x1024.png"
  #  color: "#000000"
  #  color_dark: "#000000"
  #  android_12:
  #    icon_background_color: '#000000'
  #    #image: 'assets/images/splash_android12.png'
  #    icon_background_color_dark: '#000000'
  #    #image_dark: 'assets/images/splash_android12.png'

  #  #アプリアイコン作成用
  #  flutter_launcher_icons: ^0.11.0
  #flutter_icons:
  #  android: true
  #  ios: true
  #  remove_alpha_ios: true
  #  image_path: "assets/images/icon/icon_uranai_x512.png"
  #  min_sdk_android: 21
  #  adaptive_icon_background: '#FFFFFF'
  #  adaptive_icon_foreground: "assets/images/icon/icon_uranai_x512.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
